#development:
# adapter: mysql2
# encoding: utf8
# reconnect: false
# host: localhost
# database: stweet-app
# pool: 5
# username: root
# password: root

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stweet_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock